### PR TITLE
Fix: compilation error: feature/59

### LINKED ISSUE #59: Criar Servlet de listagem de matérias.

### PR DESCRIPTION
**Pull request by EduardoCosta942**
Closes #59

### CODE REVIEW

File: src/main/java/com/example/schoolservlet/daos/StudentSubjectDAO.java [hunk 1]
```diff
@@ -202,7 +202,7 @@ public int totalCount() throws DataException {
         }
     }
 
-    public int totalCount(int studentId) throws DataException {
+    public int totalCount(int studentId) {
```
Comment (caio-marcos-ambrosio) [inline src/main/java/com/example/schoolservlet/daos/StudentSubjectDAO.java]: Adicionar exceção na interface

File: src/main/java/com/example/schoolservlet/daos/StudentSubjectDAO.java
Comment (caio-marcos-ambrosio) [inline src/main/java/com/example/schoolservlet/daos/StudentSubjectDAO.java]: Adicionar throws tbm

**Review by caio-marcos-ambrosio — DISMISSED** [review]

**Review by caio-marcos-ambrosio — APPROVED** [review]
